version: "3.9"
services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data/mongodb:/data/db
      - ./log/mongo:/log

  curzy-website:
    build: ./website
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
    env_file:
      - ./website/.env
    stdin_open: true
    tty: true
    command: npm start
