version: "3.9"
services:
  # Database for SeaCat Auth
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data/mongodb:/data/db
      - ./log/mongo:/log
      # - ./mongo-seed.js:/docker-entrypoint-initdb.d/seed.js

  curzy-app:
    build: .
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017
      - PORT=3000
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    command:
      - /bin/sh
      - -c
      - |
        npx tsc --watch & npx nodemon -L ./dist/index.js
