name: "Build and Plan"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  terraform-plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wrangler & prepare workers-dist
        working-directory: infrastructure
        run: |-
          npm install -g wrangler
          wrangler --version
          mkdir --parents workers-dist

      - name: Build workers - curzy-api
        working-directory: workers/curzy-api
        run: |-
          npm install
          npm run build
          cp -r ../dist/curzy-api ../../infrastructure/workers-dist/curzy-api

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Since Terraform cloud does not support run variables at this time.
      # Currently the only to way to pass variables is by creating a `*.auto.tfvars` variables file.
      - name: Setup Terraform variables
        working-directory: infrastructure
        id: vars
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          allowed_origins           = "${{ secrets.ALLOWED_ORIGINS }}"
          mongo_db_uri              = "${{ secrets.MONGO_DB_URI }}"
          mongodb_atlas_private_key = "${{ secrets.ATLAS_DB_PROJECT_PRIVATE_API_KEY }}"
          curzy_user_password       = "${{ secrets.MONGODB_USER_PASSWORD }}"
          EOF
          cat pipeline.auto.tfvars

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        working-directory: infrastructure
        run: terraform fmt -check -diff

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan -input=false

